<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up()
    {
        Schema::create('valuation', function (Blueprint $table) {
            $table->id('valuation_id');
            $table->smallInteger('valuation_title')->nullable();
            $table->text('valuation_first_name')->nullable();
            $table->text('valuation_surname')->nullable();
            $table->smallInteger('valuation_capacity')->nullable();
            $table->text('valuation_email')->nullable();
            $table->text('valuation_phone_home')->nullable();
            $table->text('valuation_phone_work')->nullable();
            $table->text('valuation_phone_mobile')->nullable();
            $table->text('valuation_home_address_property_apartment_number_name')->nullable();
            $table->text('valuation_home_address_property_number_name')->nullable();
            $table->text('valuation_home_address_property_address_line_1')->nullable();
            $table->text('valuation_home_address_property_address_line_2')->nullable();
            $table->text('valuation_home_address_property_suburb')->nullable();
            $table->text('valuation_home_address_property_town_city')->nullable();
            $table->string('valuation_home_address_property_postcode', 8)->nullable();
            $table->integer('valuation_home_address_property_country')->nullable();
            $table->text('valuation_property_apartment_number_name')->nullable();
            $table->text('valuation_property_number_name')->nullable();
            $table->text('valuation_property_address_line_1')->nullable();
            $table->text('valuation_property_address_line_2')->nullable();
            $table->text('valuation_property_suburb')->nullable();
            $table->text('valuation_property_town_city')->nullable();
            $table->string('valuation_property_postcode', 8)->nullable();
            $table->integer('valuation_property_country')->nullable();
            $table->smallInteger('valuation_property_availability')->nullable();
            $table->smallInteger('valuation_property_category')->nullable();
            $table->integer('valuation_property_type')->nullable();
            $table->smallInteger('valuation_property_no_bedrooms')->nullable();
            $table->smallInteger('valuation_property_no_bathrooms')->nullable();
            $table->smallInteger('valuation_property_no_receptions')->nullable();
            $table->decimal('valuation_property_price_from', 10, 2)->nullable();
            $table->decimal('valuation_property_price_to', 10, 2)->nullable();
            $table->decimal('valuation_property_price_asking', 10, 2)->nullable();
            $table->smallInteger('valuation_price_qualifier')->nullable();
            $table->integer('valuation_branch')->nullable();
            $table->integer('valuation_employee')->nullable();
            $table->integer('valuation_negotiator')->nullable();
            $table->smallInteger('valuation_status')->nullable();
            $table->smallInteger('valuation_lost_reason')->nullable();
            $table->text('valuation_notes')->nullable();
            $table->text('valuation_notes_private')->nullable();
            $table->text('valuation_value_notes')->nullable();
            $table->date('valuation_next_review_date')->nullable();
            $table->date('valuation_next_review_date_negotiator')->nullable();
            $table->date('valuation_next_review_date_lister')->nullable();
            $table->text('valuation_next_review_date_lister_notes')->nullable();
            $table->smallInteger('valuation_lead_source')->nullable();
            $table->text('valuation_lead_source_notes')->nullable();
            $table->smallInteger('valuation_occupancy')->nullable();
            $table->smallInteger('valuation_reason')->nullable();
            $table->integer('valuation_lost_to')->nullable();
            $table->decimal('valuation_lost_sale_fee', 10, 2)->nullable();
            $table->smallInteger('valuation_lost_sale_fee_type')->nullable();
            $table->decimal('valuation_property_price_marketed', 10, 2)->nullable();
            $table->smallInteger('valuation_price_qualifier_marketed')->nullable();
            $table->smallInteger('valuation_tenure_type')->nullable();
            $table->decimal('valuation_sale_fee', 10, 2)->nullable();
            $table->smallInteger('valuation_sale_fee_type')->nullable();
            $table->decimal('valuation_tenant_find_fee', 10, 2)->nullable();
            $table->smallInteger('valuation_tenant_find_fee_type')->nullable();
            $table->decimal('valuation_tenant_find_with_management_fee', 10, 2)->nullable();
            $table->smallInteger('valuation_tenant_find_with_management_fee_type')->nullable();
            $table->decimal('valuation_management_fee', 10, 2)->nullable();
            $table->smallInteger('valuation_management_fee_type')->nullable();
            $table->integer('valuation_to_landlord')->nullable();
            $table->integer('valuation_to_vendor')->nullable();
            $table->integer('valuation_to_property')->nullable();
            $table->smallInteger('valuation_condition')->nullable();
            $table->integer('valuation_contract_type')->nullable();
            $table->integer('valuation_multi_agent')->nullable();
            $table->text('valuation_multi_agent_notes')->nullable();
            $table->date('valuation_multi_agent_withdrawal_date')->nullable();
            $table->smallInteger('valuation_instruct_epc')->nullable();
            $table->integer('valuation_photographer')->nullable();
            $table->smallInteger('valuation_photographer_access')->nullable();
            $table->string('valuation_minimum_contract_period', 2)->nullable();
            $table->smallInteger('valuation_letting_service')->nullable();
            $table->integer('valuation_lister')->nullable();
            $table->smallInteger('valuation_instruction_override')->nullable();
            $table->smallInteger('valuation_instruct_video')->nullable();
            $table->text('valuation_recommendations')->nullable();
            $table->dateTime('valuation_date_created')->nullable();
            $table->dateTime('valuation_date_updated')->nullable();
            $table->integer('valuation_created_by')->nullable();
            $table->integer('valuation_updated_by')->nullable();
            $table->smallInteger('valuation_title_2')->nullable();
            $table->text('valuation_first_name_2')->nullable();
            $table->text('valuation_surname_2')->nullable();
            $table->text('valuation_email_2')->nullable();
            $table->text('valuation_phone_home_2')->nullable();
            $table->text('valuation_phone_work_2')->nullable();
            $table->text('valuation_phone_mobile_2')->nullable();
            $table->text('valuation_home_address_property_apartment_number_name_2')->nullable();
            $table->text('valuation_home_address_property_number_name_2')->nullable();
            $table->text('valuation_home_address_property_address_line_1_2')->nullable();
            $table->text('valuation_home_address_property_address_line_2_2')->nullable();
            $table->text('valuation_home_address_property_suburb_2')->nullable();
            $table->text('valuation_home_address_property_town_city_2')->nullable();
            $table->string('valuation_home_address_property_postcode_2', 8)->nullable();
            $table->integer('valuation_home_address_property_country_2')->nullable();
            $table->smallInteger('valuation_title_3')->nullable();
            $table->text('valuation_first_name_3')->nullable();
            $table->text('valuation_surname_3')->nullable();
            $table->text('valuation_email_3')->nullable();
            $table->text('valuation_phone_home_3')->nullable();
            $table->text('valuation_phone_work_3')->nullable();
            $table->text('valuation_phone_mobile_3')->nullable();
            $table->text('valuation_home_address_property_apartment_number_name_3')->nullable();
            $table->text('valuation_home_address_property_number_name_3')->nullable();
            $table->text('valuation_home_address_property_address_line_1_3')->nullable();
            $table->text('valuation_home_address_property_address_line_2_3')->nullable();
            $table->text('valuation_home_address_property_suburb_3')->nullable();
            $table->text('valuation_home_address_property_town_city_3')->nullable();
            $table->string('valuation_home_address_property_postcode_3', 8)->nullable();
            $table->integer('valuation_home_address_property_country_3')->nullable();
            $table->smallInteger('valuation_title_4')->nullable();
            $table->text('valuation_first_name_4')->nullable();
            $table->text('valuation_surname_4')->nullable();
            $table->text('valuation_email_4')->nullable();
            $table->text('valuation_phone_home_4')->nullable();
            $table->text('valuation_phone_work_4')->nullable();
            $table->text('valuation_phone_mobile_4')->nullable();
            $table->text('valuation_home_address_property_apartment_number_name_4')->nullable();
            $table->text('valuation_home_address_property_number_name_4')->nullable();
            $table->text('valuation_home_address_property_address_line_1_4')->nullable();
            $table->text('valuation_home_address_property_address_line_2_4')->nullable();
            $table->text('valuation_home_address_property_suburb_4')->nullable();
            $table->text('valuation_home_address_property_town_city_4')->nullable();
            $table->string('valuation_home_address_property_postcode_4', 8)->nullable();
            $table->integer('valuation_home_address_property_country_4')->nullable();
            $table->smallInteger('valuation_capacity_2')->nullable();
            $table->smallInteger('valuation_capacity_3')->nullable();
            $table->smallInteger('valuation_capacity_4')->nullable();
            $table->text('valuation_referral_solicitor_notes')->nullable();
            $table->text('valuation_referral_mortgage_notes')->nullable();
            $table->text('valuation_tenant_contact_details')->nullable();
            $table->text('valuation_premium_price_guide_link')->nullable();
            $table->text('valuation_status_reason')->nullable();
            $table->smallInteger('valuation_email_reminders')->nullable();
            $table->decimal('valuation_total_amount_paid_employee', 10, 2)->nullable();
            $table->decimal('valuation_property_living_space', 10, 2)->nullable();
            $table->smallInteger('valuation_property_living_space_unit')->nullable();
            $table->smallInteger('valuation_price_per_square_foot')->nullable();
            $table->smallInteger('valuation_valuer_inherited')->nullable();
            $table->text('valuation_ownership_period')->nullable();
            $table->text('valuation_extended_loft_conversion_info')->nullable();
            $table->text('valuation_major_improvements')->nullable();
            $table->text('valuation_timescale_selling')->nullable();
            $table->text('valuation_otm_details')->nullable();
            $table->text('valuation_other_vals')->nullable();
            $table->text('valuation_price_expectations')->nullable();
            $table->text('valuation_parking_arrangements')->nullable();
            $table->text('valuation_outdoor_space')->nullable();
            $table->text('valuation_instruct_video_reason')->nullable();
            $table->text('valuation_legal_owner_contact_details')->nullable();
        });
    }

    public function down()
    {
        Schema::dropIfExists('valuation');
    }
};
